export enum ErrorCode {
    NO_USER = 'NO_USER',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR',
    DEPOSIT_SAVE_ERROR = "DEPOSIT_SAVE_ERROR"
}
